### ISSUE TITLE
Feature #1 Actualizar sintaxis

### ISSUE THREAD

**Issue by rnovec** [disoftw/node-api#1]
Actualizar sintaxis del codigo que esta escrito en ES2015 cambiarlo a ES2016

- [ ] cambiar `var` por `const`
- [ ] Usar **arrow functions**: cambiar `function` por `=>`

## Pasos adicionales

- Crear una rama llamada `feature/es6`
- Commits descriptivos de las acciones realizadas

**Comment by Alvarez-P** [comment]
Yo trabajo en esta tarea

**Comment by rnovec** [comment]
Se resolvio esta tarea en #3
