### ISSUE TITLE
Feature #2  Crear README

### ISSUE THREAD

**Issue by rnovec** [disoftw/node-api#2]
Crear un README de tipo comunidad con lo siguientes secciones.

- Titulo del proyecto
- Descripción
- Prerequisitos
- Comandos de instalación
- Colaboradores

## Pasos adicionales

- Crear una rama llamada `feature/readme`
- Commits descriptivos de las acciones realizadas

**Comment by paulspartan14** [comment]
tomare esta issue y trabare en ella

**Comment by rnovec** [comment]
Resuelto por @paulspartan14 en #7
